sudo: required
services:
  - docker 

before_install:
  - docker build -t morris754/react-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true morris754/react-test npm test


after_success:
  - docker build -t morris754/multi-client ./client 
  - docker build -t morris754/multi-nginx ./nginx
  - docker build -t morris754/multi-server ./server
  - docker build -t morris754/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  - docker push morris754/multi-client 
  - docker push morris754/multi-nginx
  - docker push morris754/multi-server
  - docker push morris754/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-927416826868
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

